// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLYCRdc5RlBtVaT7U09hOQkuK2btpKddc',
    appId: '1:807205790780:android:4d54012f8dc91d68e08f39',
    messagingSenderId: '807205790780',
    projectId: 'todo-app-3155a',
    storageBucket: 'todo-app-3155a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUg5uSPoxGNh7kwRhRlh2d_8CjWti7RE',
    appId: '1:207941360530:ios:3be07b18a6da5a35283f4b',
    messagingSenderId: '207941360530',
    projectId: 'to-do-app-cc3fb',
    storageBucket: 'to-do-app-cc3fb.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqTejkux-GjWZ1spcd7n4810bPk5w9mg',
    appId: '1:807205790780:web:9f496479f37ec107e08f39',
    messagingSenderId: '807205790780',
    projectId: 'todo-app-3155a',
    authDomain: 'todo-app-3155a.firebaseapp.com',
    storageBucket: 'todo-app-3155a.firebasestorage.app',
    measurementId: 'G-QC4KFDB4SH',
  );

}